package com.POJO;

// Generated Dec 4, 2014 2:33:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * QueryInfo generated by hbm2java
 */
public class QueryInfo implements java.io.Serializable {

	private Integer queryId;
	private String queryContent;
	private String queryExpension;
	private int subtopicId;

	public QueryInfo() {
	}

	public QueryInfo(String queryContent, int subtopicId) {
		this.queryContent = queryContent;
		this.subtopicId = subtopicId;
	}

	public QueryInfo(String queryContent, String queryExpension, int subtopicId) {
		this.queryContent = queryContent;
		this.queryExpension = queryExpension;
		this.subtopicId = subtopicId;
	}

	public Integer getQueryId() {
		return this.queryId;
	}

	public void setQueryId(Integer queryId) {
		this.queryId = queryId;
	}

	public String getQueryContent() {
		return this.queryContent;
	}

	public void setQueryContent(String queryContent) {
		this.queryContent = queryContent;
	}

	public String getQueryExpension() {
		return this.queryExpension;
	}

	public void setQueryExpension(String queryExpension) {
		this.queryExpension = queryExpension;
	}

	public int getSubtopicId() {
		return this.subtopicId;
	}

	public void setSubtopicId(int subtopicId) {
		this.subtopicId = subtopicId;
	}

}
