package com.POJO;

// Generated Dec 4, 2014 2:33:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * SubtopicInfo generated by hbm2java
 */
public class SubtopicInfo implements java.io.Serializable {

	private Integer subtopicId;
	private String subtopicStmt;
	private String keywords;
	private String description;
	private int taskId;

	public SubtopicInfo() {
	}

	public SubtopicInfo(String subtopicStmt, int taskId) {
		this.subtopicStmt = subtopicStmt;
		this.taskId = taskId;
	}

	public SubtopicInfo(String subtopicStmt, String keywords,
			String description, int taskId) {
		this.subtopicStmt = subtopicStmt;
		this.keywords = keywords;
		this.description = description;
		this.taskId = taskId;
	}

	public Integer getSubtopicId() {
		return this.subtopicId;
	}

	public void setSubtopicId(Integer subtopicId) {
		this.subtopicId = subtopicId;
	}

	public String getSubtopicStmt() {
		return this.subtopicStmt;
	}

	public void setSubtopicStmt(String subtopicStmt) {
		this.subtopicStmt = subtopicStmt;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

}
