package com.POJO;

// Generated Dec 4, 2014 2:33:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * TaskInfo generated by hbm2java
 */
public class TaskInfo implements java.io.Serializable {

	private Integer taskId;
	private String taskName;
	private String taskStmt;
	private String keywords;

	public TaskInfo() {
	}

	public TaskInfo(String taskName, String taskStmt) {
		this.taskName = taskName;
		this.taskStmt = taskStmt;
	}

	public TaskInfo(String taskName, String taskStmt, String keywords) {
		this.taskName = taskName;
		this.taskStmt = taskStmt;
		this.keywords = keywords;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public String getTaskStmt() {
		return this.taskStmt;
	}

	public void setTaskStmt(String taskStmt) {
		this.taskStmt = taskStmt;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

}
