package com.POJO;

// Generated Dec 4, 2014 2:33:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;

	public UserInfo() {
	}

	public UserInfo(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
