package com.POJO;

// Generated Dec 4, 2014 2:33:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserTopicInfo generated by hbm2java
 */
public class UserTopicInfo implements java.io.Serializable {

	private Integer userTopicId;
	private int userId;
	private int subtopicId;

	public UserTopicInfo() {
	}

	public UserTopicInfo(int userId, int subtopicId) {
		this.userId = userId;
		this.subtopicId = subtopicId;
	}

	public Integer getUserTopicId() {
		return this.userTopicId;
	}

	public void setUserTopicId(Integer userTopicId) {
		this.userTopicId = userTopicId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getSubtopicId() {
		return this.subtopicId;
	}

	public void setSubtopicId(int subtopicId) {
		this.subtopicId = subtopicId;
	}

}
